os:
  - linux
  - osx

language: d

d:
  - ldc2
  - dmd

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install python-tk; fi
  - sudo pip install matplotlib


script:
  - dub test --compiler=${DC}
